gettext("Question");
gettext("Answer");
gettext("Add to set");
gettext("Add now!");
gettext("Cardset name:");
gettext("Cardset description:");
gettext("Question");
gettext("Answer");
gettext("Realy want to create that set?");
gettext("Do you realy want to delete");
gettext("Yes");
gettext("No");
gettext("View own cardsets");
gettext("Edit cardset");
gettext("Create cardset");
gettext("Modify Cardset");
gettext("Add question");
gettext("Question");
gettext("Answer");
gettext("Add to set");
gettext("Add now!");
gettext("Change name & description of a cardset");
gettext("(edit)");
gettext("(delete)");
gettext("(edit)");
gettext("(delete)");
gettext("Give me a answer!");
