<?php
$imagepath = "res/captcha";
$Zahl_1 = intval(rand(0, 9));
$Zahl_2 = intval(rand(0, 9));
$Zahl_3 = intval(rand(0, 9));
$Zahl_4 = intval(rand(0, 9));
$Zahl_5 = intval(rand(0, 9));
$cap = "$Zahl_1$Zahl_2$Zahl_3$Zahl_4$Zahl_5";
$cap_1 = $Zahl_1;
$cap_1 = ereg_replace("1","<img class=\"formmailerimg\" src=\"$imagepath/1.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("2","<img class=\"formmailerimg\" src=\"$imagepath/2.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("3","<img class=\"formmailerimg\" src=\"$imagepath/3.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("4","<img class=\"formmailerimg\" src=\"$imagepath/4.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("5","<img class=\"formmailerimg\" src=\"$imagepath/5.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("6","<img class=\"formmailerimg\" src=\"$imagepath/6.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("7","<img class=\"formmailerimg\" src=\"$imagepath/7.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("8","<img class=\"formmailerimg\" src=\"$imagepath/8.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("9","<img class=\"formmailerimg\" src=\"$imagepath/9.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_1 = ereg_replace("0","<img class=\"formmailerimg\" src=\"$imagepath/0.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_1);
$cap_2 = $Zahl_2;
$cap_2 = ereg_replace("1","<img class=\"formmailerimg\" src=\"$imagepath/1.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("2","<img class=\"formmailerimg\" src=\"$imagepath/2.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("3","<img class=\"formmailerimg\" src=\"$imagepath/3.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("4","<img class=\"formmailerimg\" src=\"$imagepath/4.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("5","<img class=\"formmailerimg\" src=\"$imagepath/5.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("6","<img class=\"formmailerimg\" src=\"$imagepath/6.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("7","<img class=\"formmailerimg\" src=\"$imagepath/7.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("8","<img class=\"formmailerimg\" src=\"$imagepath/8.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("9","<img class=\"formmailerimg\" src=\"$imagepath/9.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_2 = ereg_replace("0","<img class=\"formmailerimg\" src=\"$imagepath/0.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_2);
$cap_3 = $Zahl_3;
$cap_3 = ereg_replace("1","<img class=\"formmailerimg\" src=\"$imagepath/1.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("2","<img class=\"formmailerimg\" src=\"$imagepath/2.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("3","<img class=\"formmailerimg\" src=\"$imagepath/3.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("4","<img class=\"formmailerimg\" src=\"$imagepath/4.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("5","<img class=\"formmailerimg\" src=\"$imagepath/5.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("6","<img class=\"formmailerimg\" src=\"$imagepath/6.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("7","<img class=\"formmailerimg\" src=\"$imagepath/7.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("8","<img class=\"formmailerimg\" src=\"$imagepath/8.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("9","<img class=\"formmailerimg\" src=\"$imagepath/9.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_3 = ereg_replace("0","<img class=\"formmailerimg\" src=\"$imagepath/0.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_3);
$cap_4 = $Zahl_4;
$cap_4 = ereg_replace("1","<img class=\"formmailerimg\" src=\"$imagepath/1.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("2","<img class=\"formmailerimg\" src=\"$imagepath/2.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("3","<img class=\"formmailerimg\" src=\"$imagepath/3.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("4","<img class=\"formmailerimg\" src=\"$imagepath/4.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("5","<img class=\"formmailerimg\" src=\"$imagepath/5.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("6","<img class=\"formmailerimg\" src=\"$imagepath/6.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("7","<img class=\"formmailerimg\" src=\"$imagepath/7.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("8","<img class=\"formmailerimg\" src=\"$imagepath/8.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("9","<img class=\"formmailerimg\" src=\"$imagepath/9.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_4 = ereg_replace("0","<img class=\"formmailerimg\" src=\"$imagepath/0.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_4);
$cap_5 = $Zahl_5;
$cap_5 = ereg_replace("1","<img class=\"formmailerimg\" src=\"$imagepath/1.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("2","<img class=\"formmailerimg\" src=\"$imagepath/2.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("3","<img class=\"formmailerimg\" src=\"$imagepath/3.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("4","<img class=\"formmailerimg\" src=\"$imagepath/4.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("5","<img class=\"formmailerimg\" src=\"$imagepath/5.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("6","<img class=\"formmailerimg\" src=\"$imagepath/6.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("7","<img class=\"formmailerimg\" src=\"$imagepath/7.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("8","<img class=\"formmailerimg\" src=\"$imagepath/8.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("9","<img class=\"formmailerimg\" src=\"$imagepath/9.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_5 = ereg_replace("0","<img class=\"formmailerimg\" src=\"$imagepath/0.png\" alt=\"Bitte Captcha eintippen\"/>",$cap_5);
$cap_anzeige = "$cap_1$cap_2$cap_3$cap_4$cap_5"; 
?>